### PR TITLE
🌱 Gardening  minor issues

### LINKED ISSUE #17: [Gardening] Test-case names should be readable sentences
Didier's idea: https://github.com/EduardGomezEscandell/GoWSL/pull/15#discussion_r1066035152
> subtests can be read as sentences when being more than one word or so, like "error when blablablabla". I find it easier to read.

The idea is to have test-case names read like sentences rather than a couple keywords. This'll better contextualize test failures.

We've also agreed to make these sentences start in upper case:
```
Error when blablablabla
```

### LINKED ISSUE #18: [Gardening] Justify nolint directives
There are many `//nolint` directives that could use some better explanation, along with a justification of why they are there.

### PR DESCRIPTION
**Pull request by EduardGomezEscandell**
Minor changes that do not affect the behaviour of the package, but make it more maintainable.

Closes #17 
Closes #18 

I also added a CODEOWNERS file so I am notified when new PR are opened. I decided to only write myself in it to avoid spamming @ubuntu/wsl. I can change it if you guys want me to.

UDENG-292

### CODE REVIEW

**Review by didrocks — APPROVED** [review]
Easy changes.

One request before merging: I think the CODEOWNERS should still be the team, for long term maintenance.
Otherwise, excellent :)

**Comment by EduardGomezEscandell** [comment]
So you choose to be spammed 😅.

That aside, I'll need you to do some admin work on the repo, as I don't have enough permissions to check it:
```
Unknown owner on line 1: make sure the team @Ubuntu/WSL exists, is publicly visible, and has write access to the repository
* @Ubuntu/WSL
```

**Comment by didrocks** [comment]
> So you choose to be spammed sweat_smile.

Well, if you open your PR as spam and only ask for review one the tests pass. that should be OK :)

Admin work done.

**Comment by EduardGomezEscandell** [comment]
Great! The codeonwers file is marked as valid.

**Review by didrocks — APPROVED** [review]

**Pull request merged**
